//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int CartId { get; set; }
        public string OrderNumber { get; set; }
        public string TotalAmount { get; set; }
        public decimal ShippingCharge { get; set; }
        public string TaxAmount { get; set; }
        public int AddressId { get; set; }
        public int StatusId { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Cart Cart { get; set; }
        public virtual Status Status { get; set; }
    }
}
