//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.CartProducts = new HashSet<CartProduct>();
        }
    
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string ProductCode { get; set; }
        public string FeatureDetails { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int StockQuantity { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsDeleted { get; set; }
        public decimal Weight { get; set; }
        public string Keywords_Meta { get; set; }
        public int DispatchTime { get; set; }
        public int BrandId { get; set; }
        public bool CODApplicable { get; set; }
        public decimal ShippingCharge { get; set; }
        public string ImageURL { get; set; }
        public string Warranty { get; set; }
        public string Description { get; set; }
        public bool IsHot { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual ICollection<CartProduct> CartProducts { get; set; }
        public virtual Category Category { get; set; }
    }
}
